CREATE TABLE ACCOUNT
   ( ID INT PRIMARY KEY
   , PASSWORD VARCHAR(255));
CREATE TABLE URLS
   ( SHORT_URL VARCHAR(255)
   , URL VARCHAR(255)
   , REDIRECT_TYPE INT
   , ID INT);
CREATE TABLE STATISTIC
   ( COUNTER INT
   , URL VARCHAR(255)
   , ID INT);